export type AgentStatus = "online" | "busy" | "degraded" | "offline";
export type EventLevel = "info" | "success" | "warn" | "error";
export type EventKind =
  | "task"
  | "a2a"
  | "gateway"
  | "vault"
  | "error"
  | "deploy"
  | "llm"
  | "security";

export type Agent = {
  id: string;
  role: string;
  port: number;
  status: AgentStatus;
  model: string;
  provider: string;
  health: number;
  latencyMs: number;
  uptimePct: number;
  tokens: number;
  queue: number;
  peers: number;
  mcp: string[];
  lastSeen: number;
  throughput: number[];
  load: number;
  memoryMb: number;
  accent: string;
  summary: string;
};

export type MeshTotals = {
  online: number;
  /**
   * Queue depth is not reported by the mesh collector, so `busy`, `tasks` and
   * `tokens` are `null` when unmeasured rather than `0`. Rendering a hard zero
   * would read as a measured fact - "0% success", "0ms p95" - which is exactly
   * the kind of invented number this dashboard is meant to remove.
   */
  busy: number | null;
  degraded: number;
  offline: number;
  tasks: number | null;
  tokens: number | null;
  avgLatency: number | null;
  p95Latency: number | null;
  successRate: number | null;
  meshLinks: number;
};

export type MeshSnapshot = {
  generatedAt: number;
  source: "live" | "simulated";
  agents: Agent[];
  totals: MeshTotals;
  series: Series;
  heat: HeatCell[];
  events: ActivityEvent[];
};

export type Series = {
  labels: string[];
  throughput: number[];
  latency: number[];
  errors: number[];
  tokens: number[];
  /**
   * Provenance for the time series. `synthetic: true` means the points were
   * generated by the local engine rather than measured, and the UI must say so.
   * `resolutionSec` is the real bucket width, so consumers can slice by time
   * instead of hardcoding an assumed sample interval.
   */
  resolutionSec: number;
  synthetic: boolean;
};

export type HeatCell = {
  agent: string;
  hour: number;
  load: number;
};

export type ActivityEvent = {
  id: string;
  ts: number;
  agent: string;
  kind: EventKind;
  level: EventLevel;
  title: string;
  detail: string;
  durationMs?: number;
  tokens?: number;
};

export type TaskStatus = "backlog" | "active" | "review" | "done";
export type TaskPriority = "critical" | "high" | "normal" | "low";

export type Task = {
  id: string;
  title: string;
  brief: string;
  status: TaskStatus;
  priority: TaskPriority;
  agent: string;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  estimate: number;
  comments: number;
  blockedBy?: string;
};

export type Note = {
  id: string;
  title: string;
  path: string;
  folder: string;
  updatedAt: number;
  bytes: number;
  tags: string[];
  excerpt: string;
  body: string;
  pinned?: boolean;
};

export type MeshLink = {
  source: string;
  target: string;
  strength: number;
  latency: number;
};
