export type AgentStatus = "online" | "busy" | "degraded" | "offline";
export type EventLevel = "info" | "success" | "warn" | "error";
export type EventKind =
  | "task"
  | "a2a"
  | "gateway"
  | "vault"
  | "error"
  | "deploy"
  | "llm"
  | "security";

export type Agent = {
  id: string;
  role: string;
  /**
   * `null` when the collector did not report one. Rendering `:0` is the same
   * lie as rendering `0 ms` latency: it looks like a measurement, and the
   * registry only assigns ports to a handful of agents, so the unassigned
   * majority would read as "port 0" everywhere in the UI.
   */
  port: number | null;
  status: AgentStatus;
  model: string;
  provider: string;
  health: number;
  /**
   * The mesh collector reports gateway state, A2A reachability and document
   * presence, and nothing else. These fields are therefore `null` on the live
   * path rather than `0`/`100`: a hard `0 ms` or `100.00%` is
   * indistinguishable from a real measurement, and the point of this dashboard
   * is that an unmeasured metric is visibly unmeasured. `health` is derived from
   * reported state, so it stays a number.
   */
  latencyMs: number | null;
  uptimePct: number | null;
  tokens: number | null;
  queue: number | null;
  peers: number;
  mcp: string[];
  lastSeen: number | null;
  throughput: number[];
  load: number | null;
  memoryMb: number | null;
  accent: string;
  summary: string;
};

export type MeshTotals = {
  online: number;
  /**
   * Queue depth is not reported by the mesh collector, so `busy`, `tasks` and
   * `tokens` are `null` when unmeasured rather than `0`. Rendering a hard zero
   * would read as a measured fact - "0% success", "0ms p95" - which is exactly
   * the kind of invented number this dashboard is meant to remove.
   */
  busy: number | null;
  degraded: number;
  offline: number;
  tasks: number | null;
  tokens: number | null;
  avgLatency: number | null;
  p95Latency: number | null;
  successRate: number | null;
  meshLinks: number;
};

export type MeshSnapshot = {
  generatedAt: number;
  source: "live" | "simulated";
  agents: Agent[];
  totals: MeshTotals;
  series: Series;
  heat: HeatCell[];
  /**
   * Reporting structure from `agents/registry.json`, so the graph draws a real
   * hierarchy instead of a complete graph of the seed profiles. Absent is not
   * possible: the registry ships with the app, so a missing hierarchy means the
   * file is unreadable and that is worth failing on rather than drawing around.
   */
  hierarchy: MeshLink[];
};

export type Series = {
  labels: string[];
  throughput: number[];
  latency: number[];
  errors: number[];
  tokens: number[];
  /**
   * Provenance for the time series. `synthetic: true` means the points were
   * generated by the local engine rather than measured, and the UI must say so.
   * `resolutionSec` is the real bucket width, so consumers can slice by time
   * instead of hardcoding an assumed sample interval.
   */
  resolutionSec: number;
  synthetic: boolean;
};

export type HeatCell = {
  agent: string;
  hour: number;
  load: number;
};

export type ActivityEvent = {
  id: string;
  ts: number;
  agent: string;
  kind: EventKind;
  level: EventLevel;
  title: string;
  detail: string;
  durationMs?: number;
  tokens?: number;
};

export type TaskStatus = "backlog" | "active" | "review" | "done";
export type TaskPriority = "critical" | "high" | "normal" | "low";

export type Task = {
  id: string;
  title: string;
  brief: string;
  status: TaskStatus;
  priority: TaskPriority;
  agent: string;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  estimate: number;
  comments: number;
  blockedBy?: string;
};

export type Note = {
  id: string;
  title: string;
  path: string;
  folder: string;
  updatedAt: number;
  bytes: number;
  tags: string[];
  excerpt: string;
  body: string;
  pinned?: boolean;
};

/**
 * A line between two agents.
 *
 * This used to carry `strength` and `latency`, both produced by
 * `(i * 7 + port) % 11` and friends over a complete graph of the seven seed
 * profiles: invented numbers driving invented edge widths and an animated "hot"
 * overlay, presented as live A2A traffic. Neither is measured, so neither is
 * here. What is real is the relationship, and `kind` says which one, so the UI
 * never has to guess whether a line means traffic or reporting.
 */
export type MeshLink = {
  /** The agent that reports. */
  source: string;
  /** The agent it reports to. */
  target: string;
  kind: "reports-to";
};
